name: üì∞ News Curator

on:
  schedule:
    - cron: '30 1 * * 3,0' # Runs on Wed & Sun
  workflow_dispatch:

jobs:
  run-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Run NEWS script
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python run_news_curator.py
      - name: ‚¨ÜÔ∏è Upload news_insight.json
        run: |
          sudo apt-get -y install lftp
          lftp -c "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate no;
            open -u '${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}' -p 21 ${{ secrets.FTP_SERVER }};
            cd /public_html/map-data/;
            put -O . news_insight.json;
            bye;
          "
